### ISSUE TITLE
Stop using 0.96.

### ISSUE THREAD

**Issue by ghost** [rhodso/DiceRoll#1]
Discord.Net 0.96 is a terrible library.

Okay, maybe not, but upgrade to 1.0, since 0.96 probably will become deprecated later this year and stop working.

Just upgrade.

(You'll have to remake your entire bot though.)

**Comment by rhodso** [comment]
The tutorial I followed to make the bot used that version. I reeeeally don't want to make the entire bot again, and I have no idea how. I'll go figure it out now

**Comment by ghost** [comment]
@rhodso We have a discordapi channel where you can find help!

https://discord.gg/discord-api

**Comment by rhodso** [comment]
Now using the 1.0.1 Library. Took some getting my head round, but it's done!
